# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      id: meomeo
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Failing step
      id: demo
      run: exit 1
    - name: 🚀 Out put ready site
      id: ready_site 
      run: echo "result=success" >> $GITHUB_OUTPUT
  
  notification:
    needs: build
    runs-on: ubuntu-latest
    if: always() # set "always"
    steps:
     - name: 🔔 Send Push Notification
       uses: dinhphuc/tictop-github-action@main
       env:
           API_URL: ${{ secrets.API_URL }}
           API_KEY: ${{ secrets.API_KEY }}
           MESSAGE: Deploy to Alpha by @${{ github.actor }} - ${{ (needs.build.result == 'success') && 'Success' || 'Failure' }}
           TITLE: Deploy to Alpha by @${{ github.actor }}
           DESCRIPTION: Deploy to Alpha by @${{ github.actor }}
